# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ssucom
email: sumin.lee@nhnent.com
author: 이수민
description: Happy Coding
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ssucom502.github.io" # the base hostname & protocol for your site
github_username:  ssucom502

#highlighter: pygments
# Build settings
markdown: redcarpet

redcarpet:
    extensions: 
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap